bean_brew/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include("home.urls")),
    path("user/",include("userauths.urls"))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root= settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from home.views  import index
from home.views import store
from home.views import about

app_name = "home"

urlpatterns = [
    path("",index,name = "index"),
    path('store/',store,name='store'),
    path('about/',about,name='about'),
]

userauths/urls.py
from django.urls import path
from userauths import views

app_name = "userauths"

urlpatterns = [
    path("register/",views.register_view,name= 'register'),
    path("login/",views.LoginView,name= 'login'),
    path("logout/",views.LogoutView,name= 'logout')
]

home/models.py
from django.db import models

# Create your models here.
class reservation(models.Model):

    CITY =[
        ('Harrogate','Harrogate'),
        ('Leeds','Leeds'),
        ('Knaresborough Castle','Knaresborough')
    ]
    name = models.CharField(max_length = 50)
    email = models.EmailField()
    phone = models.IntegerField()
    restaurant = models.CharField(max_length = 100,choices=CITY)
    number_persons = models.IntegerField()
    date = models.DateField()
    time = models.TimeField(null=True,blank = True)
    

    def __str__(self):
        return self.name

userauths/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.
class User(AbstractUser):
    email = models.EmailField(unique = True)
    usern = models.CharField(max_length = 100)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username']

    def __str__(self):
        return self.username

home/forms.py
from django import forms
from .models import reservation

class ReserveTableForm(forms.ModelForm):
    class Meta:
        model = reservation
        fields = '__all__'

userauths/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from userauths.models import User

class UserRegisterForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username','email']   

home/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import reservation
from .forms import ReserveTableForm
from home.models import reservation

# Create your views here.
def index(request):
    return render(request,"home/homepage.html")



def about(request):
    return render(request,'about/About.html')

def store(request):
    reserve_form = ReserveTableForm()

    if request.method == 'POST':
        reserve_form = ReserveTableForm(request.POST)
        if reserve_form.is_valid():
            reserve_form.save()

    context = {'form':reserve_form}
    return render(request,'Store/services.html',context)

userauths/views.py
from django.shortcuts import redirect,render
from userauths.forms import UserRegisterForm
from django.contrib.auth import login,authenticate,logout
from django.contrib import messages
from django.conf import settings
from userauths.models import User





# Create your views here.
def register_view(request):
    if request.method == "POST":
        form = UserRegisterForm(request.POST or None)
        if form.is_valid():
            new_user = form.save()
            username = form.cleaned_data.get('username')
            messages.success(request,f"Hey {username}, your account was created successfully!")
            new_user = authenticate(username = form.cleaned_data['email'],
                                    password= form.cleaned_data['password1'])
            login(request,new_user)
            return redirect("home:index")
    else:
        form = UserRegisterForm()
        

    context = {
        'form': form,
    }
    return render(request,"userauths/register.html",context)

def LoginView(request):
    if request.user.is_authenticated:
        return redirect("home:index")
    
    if request.method == 'POST':
        email = request.POST.get('email')
        password = request.POST.get('password')

        try:
            user = User.objects.get(email = email)
            user = authenticate(request,email=email,password = password)
        
            if user is not None:
                login(request,user)
                messages.success(request,f"You are logged in!")
                return redirect("home:index")
            else:
                messages.warning(request,f'User does not exist!,Create an account')
        except:
            messages.warning(request,f'User with {email} does not exist!')

       
            
        
    return render(request,"userauths/login.html")

def LogoutView(request):
    logout(request)
    messages.warning(request,f'You successfully logged out!')
    return redirect("userauths:login")

templates/Store/services.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'services.css' %}">
    <link href="https://fonts.cdnfonts.com/css/garet" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css">

</head>
<body>
    
    <header>
       
        <h2 class="head"><img src="{% static 'images/logo.png' %}" alt=""></h2>
        <nav class="Navigation">
            <a class="home" href="{% url 'home:index' %}">Home</a> <!-- -->
            <a class="services" href="{% url 'home:store' %}">Store</a>
            <a class = "about" href="{% url 'home:about' %}">About</a>
            
            
        </nav> 
        <img src="{% static 'images/profile.png' %}" class="ProfilePicture" onclick="toggleMenu()">
            <div class="submenu-wrap" id="subMenu">
                <div class="submenu">
                    <div class="user-info">
                        <img src="{% static 'images/profile.png' %}" class="profile-pic">
                        <h2>Profile Menu</h2>
                    </div>
                    <hr>
                    <a href="#" class="submenu-link">
                        <img src="{% static 'images/profile2.png' %}" class="profile-pic1">
                        <p>Edit Profile</p>
                        <span>></span>
                    </a>
                    <a href="{% url 'userauths:register' %}" class="submenu-link">
                        <img src="{% static 'images/sign-up.png' %}" class="profile-pic1">
                        <p>Register</p>
                        <span>></span>
                    </a>
                    <a href="{% url 'userauths:login' %}" class="submenu-link">
                        <img src="{% static 'images/login.png' %}" class="profile-pic1">
                        <p>Login</p>
                        <span>></span>
                    </a>
                    {% if request.user.is_authenticated %}
                    <a href="{% url 'userauths:logout' %}" class="submenu-link">
                        <img src="{% static 'images/logout.png' %}" class="profile-pic1">
                        <p>Sign Out</p>
                        <span>></span>
                    </a>
                    {% else %}
                    <a href="#"></a>
                    {% endif %}
                </div>
            </div>
            <div class="submenu-wrap1" id="subMenu1">
                <div class="submenu1">
                            <h2>Book a table</h2>
                            <form action="" method="POST">
                                {% csrf_token %}
                                
                                <div class="input_box">
                                    {{form.name}}
                                    <label>Name</label>
                                </div>
                                <div class="input_box">
                                    {{form.email}}
                                    <label>Email</label>
                                </div>
                                <div class="input_box">
                                    {{form.phone}}
                                    <label>phone</label>
                                </div>
                                <div class="input_box">
                                    {{form.restaurant}}
                                    <label>restaurant</label>
                                </div>
                                <div class="input_box">
                                    {{form.number_persons}}
                                    <label>No.Persons</label>
                                </div>
                                <div class="input_box">
                                    {{form.date}}
                                    <label>Date</label>
                                </div>
                                <div class="input_box">
                                    {{form.time}}
                                    <label>Time</label>
                                </div>
                                <Button class="btn" type="submit">Submit</Button>
                                
                            </form>
            </div>
        

                <div class="custom-shape-divider-bottom-1706826610">
                    <svg data-name="Layer 1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1200 120" preserveAspectRatio="none">
                        <path d="M0,0V46.29c47.79,22.2,103.59,32.17,158,28,70.36-5.37,136.33-33.31,206.8-37.5C438.64,32.43,512.34,53.67,583,72.05c69.27,18,138.3,24.88,209.4,13.08,36.15-6,69.85-17.84,104.45-29.34C989.49,25,1113-14.29,1200,52.47V0Z" opacity=".25" class="shape-fill"></path>
                        <path d="M0,0V15.81C13,36.92,27.64,56.86,47.69,72.05,99.41,111.27,165,111,224.58,91.58c31.15-10.15,60.09-26.07,89.67-39.8,40.92-19,84.73-46,130.83-49.67,36.26-2.85,70.9,9.42,98.6,31.56,31.77,25.39,62.32,62,103.63,73,40.44,10.79,81.35-6.69,119.13-24.28s75.16-39,116.92-43.05c59.73-5.85,113.28,22.88,168.9,38.84,30.2,8.66,59,6.17,87.09-7.5,22.43-10.89,48-26.93,60.65-49.24V0Z" opacity=".5" class="shape-fill"></path>
                        <path d="M0,0V5.63C149.93,59,314.09,71.32,475.83,42.57c43-7.64,84.23-20.12,127.61-26.46,59-8.63,112.48,12.24,165.56,35.4C827.93,77.22,886,95.24,951.2,90c86.53-7,172.46-45.71,248.8-84.81V0Z" class="shape-fill"></path>
                    </svg>
                </div>
       
        
    </header>
    <section>
        <p class="heading">Services</p>
        <div class="container">
            <div class="boxes">
                <h1>Booking table</h1>
                <img src="{% static 'images/frapp.png' %}" alt="">
                <button onclick="toggleMenu1()">Explore</button>
            </div>
            <div class="boxes">
                <h1>Online lessons</h1>
                <img src="{% static 'images/frapp.png' %}" alt="">
                <button>Explore</button>
            </div>
            <div class="boxes">
                <h1>Order menu items</h1>
                <img src="{% static 'images/frapp.png' %}" alt="">
                <button>Explore</button>
            </div>
            <div class="boxes">
                <h1>Custom Hampers</h1>
                <img src="{% static 'images/frapp.png' %}" alt="">
                <button>Explore</button>
            </div>

        </div>

    </section>
    <footer class="footer">
        <div class="cont">
            <div class="row">
                <div class="footer-col">
                    <h4>Bean and Brew</h4>
                    <ul>
                        <li><a href="#">About us</a></li>
                        <li><a href="#">Our Store</a></li>
                        <li><a href="#">Privacy Policy</a></li>
                        <li><a href="#">Terms and conditions</a></li>
                    </ul>
                </div>
                <div class="footer-col">
                    <h4>Online store</h4>
                    <ul>
                        <li><a href="#">Booking table</a></li>
                        <li><a href="#">Pre-order coffee</a></li>
                        <li><a href="#">Custom hamper ordering</a></li>
                        <li><a href="#">Online cooking lessons</a></li>
                        <li><a href="#">Order Baked goods for collection</a></li>
                    </ul>
                </div>
                <div class="footer-col">
                    <h4>Social Media</h4>
                    <div class="social-links">
                        <a href="#"><i class="fab fa-facebook-f"></i></a>
                        <a href="#"><i class="fab fa-twitter"></i></a>
                        <a href="#"><i class="fab fa-instagram"></i></a>
                    </div>
                    
                </div>
            </div>
        </div>
    </footer>
    <script>
        let subMenu = document.getElementById("subMenu");

        function toggleMenu(){
            subMenu.classList.toggle("open-menu");
        }
        let subMenu1 = document.getElementById("subMenu1");

        function toggleMenu1(){
            subMenu1.classList.toggle("open-menu");
        }
    </script>
    
    
    
    
</body>
</html>

templates/about/About.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'About.css' %}">
    <title>Document</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css">
</head>
<body>
    <header>
        <h2 class="head"><img src="{% static 'images/logo.png' %}" alt=""></h2>
        <nav class="Navigation">
            <a class="home" href="{% url 'home:index' %}">Home</a> <!-- -->
            <a class="services" href="{% url 'home:store' %}">Store</a>
            <a class = "about" href="{% url 'home:about'%}">About</a>
            
            
            
        </nav> 
        <img src="{% static 'images/profile.png' %}" class="ProfilePicture" onclick="toggleMenu()">

            <div class="submenu-wrap" id="subMenu">
                <div class="submenu">
                    <div class="user-info">
                        <img src="{% static 'images/profile.png' %}" class="profile-pic">
                        <h2>Profile Menu</h2>
                    </div>
                    <hr>
                    <a href="#" class="submenu-link">
                        <img src="{% static 'images/profile2.png' %}" class="profile-pic1">
                        <p>Edit Profile</p>
                        <span>></span>
                    </a>
                    <a href="{% url 'userauths:register' %}" class="submenu-link">
                        <img src="{% static 'images/sign-up.png' %}" class="profile-pic1">
                        <p>Register</p>
                        <span>></span>
                    </a>
                    <a href="{% url 'userauths:login' %}" class="submenu-link">
                        <img src="{% static 'images/login.png' %}" class="profile-pic1">
                        <p>Login</p>
                        <span>></span>
                    </a>
                    {% if request.user.is_authenticated %}
                    <a href="{% url 'userauths:logout' %}" class="submenu-link">
                        <img src="{% static 'images/logout.png' %}" class="profile-pic1">
                        <p>Sign Out</p>
                        <span>></span>
                    </a>
                    {% else %}
                    <a href="#"></a>
                    {% endif %}
                </div>
    </header>
    <section>
        <div class="text">
            <h4>About us</h4>
            <p>Enter your text here</p>
        </div>

    </section>
    <footer class="footer">
        <div class="cont">
            <div class="row">
                <div class="footer-col">
                    <h4>Bean and Brew</h4>
                    <ul>
                        <li><a href="#">About us</a></li>
                        <li><a href="#">Our Store</a></li>
                        <li><a href="#">Privacy Policy</a></li>
                        <li><a href="#">Terms and conditions</a></li>
                    </ul>
                </div>
                <div class="footer-col">
                    <h4>Online store</h4>
                    <ul>
                        <li><a href="#">Booking table</a></li>
                        <li><a href="#">Pre-order coffee</a></li>
                        <li><a href="#">Custom hamper ordering</a></li>
                        <li><a href="#">Online cooking lessons</a></li>
                        <li><a href="#">Order Baked goods for collection</a></li>
                    </ul>
                </div>
                <div class="footer-col">
                    <h4>Social Media</h4>
                    <div class="social-links">
                        <a href="#"><i class="fab fa-facebook-f"></i></a>
                        <a href="#"><i class="fab fa-twitter"></i></a>
                        <a href="#"><i class="fab fa-instagram"></i></a>
                    </div>
                    
                </div>
            </div>
        </div>
    </footer>
    <script>
        let subMenu = document.getElementById("subMenu");

        function toggleMenu(){
            subMenu.classList.toggle("open-menu");
        }
    </script>
</body>
</html>

templates/home/homepage.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Bean and brew</title>
    <link rel="stylesheet" href="{% static 'homepage.css' %}">
    <link href="https://fonts.cdnfonts.com/css/garet" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
    
</head>
<body>
    <section class="top">
        <header>
            <h2 class="head"><img src="{% static 'images/logo.png'%}" alt=""></h2>
            <nav class="Navigation">
                <a class="home" href="{% url 'home:index' %}">Home</a> <!-- -->
                <a class="services" href="{% url 'home:store'%}">Store</a>
                <a class = "about" href="{% url 'home:about' %}">About</a>

                
                
            </nav> 
            <img src="{% static 'images/profile.png' %}" class="ProfilePicture" onclick="toggleMenu()">

            <div class="submenu-wrap" id="subMenu">
                <div class="submenu">
                    <div class="user-info">
                        <img src="{% static 'images/profile.png' %}" class="profile-pic">
                        <h2>Profile Menu</h2>
                    </div>
                    <hr>
                    <a href="#" class="submenu-link">
                        <img src="{% static 'images/profile2.png' %}" class="profile-pic1">
                        <p>Edit Profile</p>
                        <span>></span>
                    </a>
                    <a href="{% url 'userauths:register' %}" class="submenu-link">
                        <img src="{% static 'images/sign-up.png' %}" class="profile-pic1">
                        <p>Register</p>
                        <span>></span>
                    </a>
                    <a href="{% url 'userauths:login' %}" class="submenu-link">
                        <img src="{% static 'images/login.png' %}" class="profile-pic1">
                        <p>Login</p>
                        <span>></span>
                    </a>
                    {% if request.user.is_authenticated %}
                    <a href="{% url 'userauths:logout' %}" class="submenu-link">
                        <img src="{% static 'images/logout.png' %}" class="profile-pic1">
                        <p>Sign Out</p>
                        <span>></span>
                    </a>
                    {% else %}
                    <a href="#"></a>
                    {% endif %}
                </div>
        </header>
        
        <div class="custom-shape-divider-bottom-1701959631">
            <svg data-name="Layer 1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1200 120" preserveAspectRatio="none">
                <path d="M0,0V46.29c47.79,22.2,103.59,32.17,158,28,70.36-5.37,136.33-33.31,206.8-37.5C438.64,32.43,512.34,53.67,583,72.05c69.27,18,138.3,24.88,209.4,13.08,36.15-6,69.85-17.84,104.45-29.34C989.49,25,1113-14.29,1200,52.47V0Z" opacity=".25" class="shape-fill"></path>
                <path d="M0,0V15.81C13,36.92,27.64,56.86,47.69,72.05,99.41,111.27,165,111,224.58,91.58c31.15-10.15,60.09-26.07,89.67-39.8,40.92-19,84.73-46,130.83-49.67,36.26-2.85,70.9,9.42,98.6,31.56,31.77,25.39,62.32,62,103.63,73,40.44,10.79,81.35-6.69,119.13-24.28s75.16-39,116.92-43.05c59.73-5.85,113.28,22.88,168.9,38.84,30.2,8.66,59,6.17,87.09-7.5,22.43-10.89,48-26.93,60.65-49.24V0Z" opacity=".5" class="shape-fill"></path>
                <path d="M0,0V5.63C149.93,59,314.09,71.32,475.83,42.57c43-7.64,84.23-20.12,127.61-26.46,59-8.63,112.48,12.24,165.56,35.4C827.93,77.22,886,95.24,951.2,90c86.53-7,172.46-45.71,248.8-84.81V0Z" class="shape-fill"></path>
            </svg>
        </div>
        <div class="logos">
            <div class="logo">
                <div class="stat">
                    <svg width = "300" height = "150">
                        <path id="curve" d="M 0 120 C 0 120, 130 0, 260 120"></path>
                        <text class = "text" text-anchor = "middle">
                            <textpath class="mono" href = "#curve" startOffset = "50%">have a sip,survive the week</textpath>
                        </text>
                    </svg>
                </div>
                <p class="branding">Bean and Brew</p>
            </div>
            <div>
                <button class = "login_register" onclick="toggleMenu()">Login/Register</button>
                <img class = "arrow" src="{%static 'images/arrow.png' %}" alt="">
            </div>
        </div>
    </section>
    {% if messages %}
            {% for message in messages %}
                <div class="alert-{{message.tags}} role='alert'">
                    <p>{{ message }}</p>
                </div>
            {% endfor %}
    {% endif %}

    <script>
        // Wait for the document to be fully loaded
        $(document).ready(function() {
            // Select all elements with a class starting with 'alert-'
            var alerts = $("[class^='alert-']");
            
            // Close the alerts after 3 seconds
            setTimeout(function() {
                alerts.fadeOut();
            }, 3000);
        });
    </script>
    
    <section class="menu">
        <div class = "menusystem">
            <h1>What's New </h1>
            <p>Discover our new range of fair-trade coffee and organic milk products</p>
        </div>
        <div class="gridwrapper">
            <div class="item">
                <p>Caramel Frappuchino</p>
                <img src="{%static 'images/frapp.png' %}" alt="">
                <button>Explore</button>
                
            </div>
            <div class="item">
                <p>Pumpkin Iced latte</p>
                <img src="{%static 'images/Pumpkin.png' %}" alt="">
                <button>Explore</button>
            </div>
            <div class="item">
                <p>Fruit smoothies</p>
                <img src="{%static 'images/Fruit.png' %}" alt="">
                <button>Explore</button>
            </div>
        </div>
        
    </section>
    <footer class="footer">
        <div class="cont">
            <div class="row">
                <div class="footer-col">
                    <h4>Bean and Brew</h4>
                    <ul>
                        <li><a href="#">About us</a></li>
                        <li><a href="#">Our Store</a></li>
                        <li><a href="#">Privacy Policy</a></li>
                        <li><a href="#">Terms and conditions</a></li>
                    </ul>
                </div>
                <div class="footer-col">
                    <h4>Online store</h4>
                    <ul>
                        <li><a href="#">Booking table</a></li>
                        <li><a href="#">Pre-order coffee</a></li>
                        <li><a href="#">Custom hamper ordering</a></li>
                        <li><a href="#">Online cooking lessons</a></li>
                        <li><a href="#">Order Baked goods for collection</a></li>
                    </ul>
                </div>
                <div class="footer-col">
                    <h4>Social Media</h4>
                    <div class="social-links">
                        <a href="#"><i class="fab fa-facebook-f"></i></a>
                        <a href="#"><i class="fab fa-twitter"></i></a>
                        <a href="#"><i class="fab fa-instagram"></i></a>
                    </div>
                    
                </div>
            </div>
        </div>
    </footer>
    
    <script>
        let subMenu = document.getElementById("subMenu");

        function toggleMenu(){
            subMenu.classList.toggle("open-menu");
        }
    </script>
    
    
    


  
</body>
</html>

templates/userauths/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
    <link href="https://fonts.cdnfonts.com/css/garet" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'login.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
    
</head>
<body>
    <header>
        <h2 class="head"><img src="{% static 'images/logo.png' %}" alt=""></h2>
        <nav class="Navigation">
            <a href="{% url 'home:index' %}">Home</a>
            <a href="">About</a>
            <a href="">Services</a>
        </nav> 
    </header>
    {% if messages %}
                    {% for message in messages %}
                    <div class="alert-{{message.tags}}">
                        <p>{{ message }}</p>
                    </div>
                    {% endfor %}
    {% endif %}
    <div class="container2">
        <div class="wrapper">
            <div class="login">
                <h2>Login</h2>
                <form action="" method="POST">
                    {% csrf_token %}
                    <div class="input_box">
                        <input type="email"  name="email" required>
                        <label>Email</label>
                    </div>
                    <div class="input_box">
                        <input type="password" name="password" required >
                        <label >password</label>
                    </div>
                    <div class="Remember-forgot">
                        <label ><input type="checkbox">Remember me</label>
                        <a href="">Forgot password?</a>
                        
                    </div>
                    <button class = "btn">Login</button>
                    <div class="register">
                        <p>Dont have an account? <a class="register-link" href="{% url 'userauths:register' %}">Register</a></p>
            
                    </div>
                    
                </form>
                
            </div>
        </div>

    </div>
    
    
    <footer class="footer">
        <div class="cont">
            <div class="row">
                <div class="footer-col">
                    <h4>Bean and Brew</h4>
                    <ul>
                        <li><a href="#">About us</a></li>
                        <li><a href="#">Our Store</a></li>
                        <li><a href="#">Privacy Policy</a></li>
                        <li><a href="#">Terms and conditions</a></li>
                    </ul>
                </div>
                <div class="footer-col">
                    <h4>Online store</h4>
                    <ul>
                        <li><a href="#">Booking table</a></li>
                        <li><a href="#">Pre-order coffee</a></li>
                        <li><a href="#">Custom hamper ordering</a></li>
                        <li><a href="#">Online cooking lessons</a></li>
                        <li><a href="#">Order Baked goods for collection</a></li>
                    </ul>
                </div>
                <div class="footer-col">
                    <h4>Social Media</h4>
                    <div class="social-links">
                        <a href="#"><i class="fab fa-facebook-f"></i></a>
                        <a href="#"><i class="fab fa-twitter"></i></a>
                        <a href="#"><i class="fab fa-instagram"></i></a>
                    </div>
                    
                </div>
            </div>
        </div>
    </footer>
    <script>
        // Wait for the document to be fully loaded
        $(document).ready(function() {
            // Select all elements with a class starting with 'alert-'
            var alerts = $("[class^='alert-']");
            
            // Close the alerts after 3 seconds
            setTimeout(function() {
                alerts.fadeOut();
            }, 3000);
        });
    </script>
</body>
</html>